---
- name: Listen for events on a webhook
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5000
        
  rules:
    - name: ChatOps Conversation
      condition: event.payload.message is search("!netops setup vlan", ignorecase=false) or event.payload.text is search("!netops setup vlan", ignorecase=false)
      action:
        run_workflow_template:
          name: "Asignación de VLAN"
          organization: Default
