##example
---
- name: Port State Event from switches

  hosts: all
  sources:
   - ansible.eda.kafka:
       host: broker
       port: 9092
       topic: network

  rules:
  
   - name: BGP change detected
     condition: event.fields.session_state == "IDLE"
     action:
       run_playbook:
        name: bgp_troubleshooting.yml
        post_events: true

   - name: Notify Chat
     condition: event.status is defined
     action:
        run_playbook:
          name: notify_chat.yml
