---
- name: Regex Processing for hostnames
  hosts: all
  #connection: local
  gather_facts: false
  vars:
    eda_input: "{{ ansible_eda.event.payload.text }}"  # access event payload
  #  regex_pattern: '\b(\w+\.cenco\.corp)\b'          # can supply via vars.ym

  tasks:
    - name: Extract switch name from text
      set_fact:
        cacheable: yes
        switch_devices: "{{ eda_input | regex_findall(regex_pattern) }}"
        regex_proc: done
        prompt: "{{ eda_input }}"
