---
- name: Check Switch
  hosts: "{{ ansible_eda.event.switch_devices }}"
  gather_facts: false
  connection: httpapi
  vars:
   ansible_httpapi_port: 443
   ansible_httpapi_use_ssl: true
   ansible_httpapi_validate_certs: false

  tasks:

    - name: Check device reacheability
      cisco.ios.ios_ping:
        dest: "{{ ansible_eda.event.switch_devices }}"
        register: pingstatus

    - name: Send notification message via Mattermost
      community.general.mattermost:
        url: ## Add URL
        api_key: ## Add Token
        attachments:
          - text: "Estado del dispositivo {{ ansible_eda.event.switch_devices }}"
            color: '#ff00dd'
            title: Device Check
            fields:
             - title: Inventario
               value: "Switch identificado en la CMDB"
               short: true
             - title: Conectividad
               value: "{{ pingstatus }}"
               short: true
        delegate_to: localhost 
