---
- name: Check Switch
  hosts: localhost
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
   eda_input: "{{ ansible_eda.event.payload.text }}"
   #ansible_become: yes
   #ansible_become_method: enable
   #ansible_network_os: cisco.ios.ios
   #ansible_user=my_ios_user
   #ansible_password=my_ios_password

  tasks:

   # - name: Check device reacheability
   #   cisco.ios.ios_ping:
   #     dest: "{{ ansible_eda.event.switch_devices }}"
   #     register: pingstatus
       
    - name: eda_input
      debug: 
        msg: "{{ eda_input }}"

