---
- name: Check Switch
  hosts: localhost
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    ansible_become: yes
    ansible_become_method: enable
    ansible_network_os: cisco.ios.ios
   #ansible_user=my_ios_user
   #ansible_password=my_ios_password

  tasks:

    - name: Check device reacheability
      cisco.ios.ios_ping:
        dest: "{{ ansible_eda.event.switch_devices }}"
        register: pingstatus

    - name: Send notification message via Mattermost
      community.general.mattermost:
        url: ## Add URL
        api_key: ## Add Token
        attachments:
          - text: "Estado del dispositivo {{ ansible_eda.event.switch_devices }}"
            color: '#ff00dd'
            title: Device Check
            fields:
             - title: Inventario
               value: "Switch identificado en la CMDB"
               short: true
             - title: Conectividad
               value: "{{ pingstatus }}"
               short: true
        delegate_to: localhost 
