---
- name: Check Switch
  hosts: localhost
  gather_facts: false
  connection: ansible.netcommon.network_cli
  vars:
    eda_input: "{{ ansible_eda.event.payload.text }}" 
    newprompt: "{{ prompt }}"
    newtargetdevice: "{{ switch_devices }}"
   #ansible_become: yes
   #ansible_become_method: enable
   #ansible_network_os: cisco.ios.ios
   #ansible_user=my_ios_user
   #ansible_password=my_ios_password

  tasks:

   # - name: Check device reacheability
   #   cisco.ios.ios_ping:
   #     dest: "{{ ansible_eda.event.switch_devices }}"
   #     register: pingstatus
  #vars:
   # eda_input: "{{ ansible_eda.event.payload.text }}"  # access event payload
    #regex_pattern: '\b(\w+\.mydomain\.com)\b'          # can supply via vars.yml

  #tasks:

    - name: Extract switch name from text
      set_fact:
        switch_devices: "{{ newtargetdevice  }}"
        cacheable: yes
       
    - debug: 
      msg: "{{ newtargetdevice }}"

    - debug: 
      msg: "newprompt: {{ newprompt }}"
