---
- name: Check Switch
  hosts: "{{ ansible_eda.event.switch_devices }}"
  gather_facts: false
  connection: httpapi
  vars:
   ansible_httpapi_port: 443
   ansible_httpapi_use_ssl: true
   ansible_httpapi_validate_certs: false

  tasks:

    - name: Check device reacheability
       ios_ping:
         dest: 10.10.10.10

    - name: Send notification message via Mattermost
       community.general.mattermost:
         url: ## Add URL
         api_key: ## Add Token
         attachments:
           - text: "!!!!!! ALERT !!!!!!"
             color: '#ff00dd'
             title: BGP ERROR
             fields:
              - title: Issue
                value: "BGP {{ ansible_eda.event.fields.session_state }} Error!"
                short: true
              - title: Details
                value: "Neighbor Address: {{ ansible_eda.event.tags.neighbor_address }} from switch {{ ansible_eda.event.name }}"
                short: true
         delegate_to: localhost 
