---
- name: Send notification message via Mattermost
  community.general.mattermost:
    url: http://localhost:8065/hooks/
    api_key: eqgboi4rwfd75c97w8wa93u7dy
    attachments:
      - text: "Estado del dispositivo {{ ansible_eda.event.switch_devices }}"
        color: '#ff00dd'
        title: Device Check
        fields:
          - title: Inventario
            value: "Switch identificado en la CMDB"
            short: true
          - title: Conectividad
            value: "{{ eda_input }}"
            short: true
    delegate_to: localhost 
